const schemes=[
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,// inverted me matt likhna ye
				min_income:234223, // aur ye bhi
				caste:"general",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"agriculture",
				scheme_url:"gov ki website ka link",
			},
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,
				min_income:234223,
				caste:"general",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"agriculture",
				scheme_url:"gov ki website ka link",
			},
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,
				min_income:234223,
				caste:"general",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"agriculture",
				scheme_url:"gov ki website ka link",
			},
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,
				min_income:234223,
				caste:"general",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"agriculture",
				scheme_url:"gov ki website ka link",
			},
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,
				min_income:234223,
				caste:"general",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"business",
				scheme_url:"gov ki website ka link",
			},
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,
				min_income:234223,
				caste:"sc",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"business",
				scheme_url:"gov ki website ka link",
			},
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,
				min_income:234223,
				caste:"sc",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"business",
				scheme_url:"gov ki website ka link",
			},
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,
				min_income:234223,
				caste:"st",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"business",
				scheme_url:"gov ki website ka link",
			},
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,
				min_income:234223,
				caste:"st",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"business",
				scheme_url:"gov ki website ka link",
			},
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,
				min_income:234223,
				caste:"st",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"education",
				scheme_url:"gov ki website ka link",
			},
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,
				min_income:234223,
				caste:"st",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"education",
				scheme_url:"gov ki website ka link",
			},
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,
				min_income:234223,
				caste:"st",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"health",
				scheme_url:"gov ki website ka link",
			},
			{
				scheme_name:"scheme ka naaam",
				about_scheme:"scheme ke baarein me",
				min_age:20,
				min_income:234223,
				caste:"st",
				gender:"vo bhi small me no spaces (male) aisa",
				scheme_sector:"banking",
				scheme_url:"gov ki website ka link",
			},
			//aage aise hi add karte rehna
]

export default schemes;