const schemes=[
    {
        scheme_name:"Kisan Samman Nidhi Yojana",
        about_scheme:"This scheme provides financial assistance to farmers for their agricultural needs.",
        min_age:18,
        min_income:60000,
        caste:"All",
        gender:"All",
        scheme_sector:"agriculture",
        scheme_url:"https://pmkisan.gov.in/",
        scheme_img_url:"https://example.com/images/kisan_samman_nidhi.jpg"
    },
    {
        scheme_name:"Pradhan Mantri Awas Yojana",
        about_scheme:"This scheme provides affordable housing to the economically weaker sections of the society.",
        min_age:21,
        min_income:120000,
        caste:"general",
        gender:"All",
        scheme_sector:"agriculture",
        scheme_url:"https://pmaymis.gov.in/",
        scheme_img_url:"https://example.com/images/pm_awas_yojana.jpg"
    },
    {
        scheme_name:"Pradhan Mantri Jan Dhan Yojana",
        about_scheme:"This scheme aims to provide financial inclusion to all households in India by providing them with a bank account, a RuPay debit card and an insurance cover.",
        min_age:18,
        min_income:0,
        caste:"general",
        gender:"All",
        scheme_sector:"business",
        scheme_url:"https://pmjdy.gov.in/",
        scheme_img_url:"https://example.com/images/pm_jan_dhan_yojana.jpg"
    },
    {
        scheme_name:"Sukanya Samriddhi Yojana",
        about_scheme:"This scheme is designed for the welfare of the girl child and encourages parents to save for their girl child's future education and marriage expenses.",
        min_age:0,
        min_income:25000,
        caste:"general",
        gender:"Female",
        scheme_sector:"business",
        scheme_url:"https://www.indiapost.gov.in/VAS/Pages/Content/Sukanya-Samriddhi-Account.aspx",
        scheme_img_url:"https://example.com/images/sukanya_samriddhi_yojana.jpg"
    },
    {
        scheme_name:"National Pension System",
        about_scheme:"This scheme is a voluntary contribution pension system for individuals aged 18 to 60 years and aims to provide retirement income to its subscribers.",
        min_age:18,
        min_income:0,
        caste:"sc",
        gender:"All",
        scheme_sector:"banking",
        scheme_url:"https://www.npscra.nsdl.co.in/",
        scheme_img_url:"https://example.com/images/national_pension_system.jpg"
    },
    {
        scheme_name:"Pradhan Mantri Fasal Bima Yojana",
        about_scheme:"This scheme aims to provide insurance coverage and financial support to farmers in the event of crop damage due to natural calamities, pests or diseases.",
        min_age:18,
        min_income:0,
        caste:"sc",
        gender:"All",
        scheme_sector:"agriculture",
        scheme_url:"https://pmfby.gov.in/",
        scheme_img_url:"https://example.com/images/pm_fasal_bima_yojana.jpg"
    },
    {
        scheme_name:"Digital India",
        about_scheme:"This scheme aims to transform India into a digitally empowered society and knowledge economy.",
        min_age:0,
        min_income:0,
        caste:"st",
        gender:"All",
        scheme_sector:"education",
        scheme_url:"https://www.digitalindia.gov.in/",
        scheme_img_url:"https://example.com/images/digital_india.jpg"
    }]

// const schemes=[
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,// inverted me matt likhna ye
// 				min_income:234223, // aur ye bhi
// 				caste:"general",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"agriculture",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,
// 				min_income:234223,
// 				caste:"general",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"agriculture",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,
// 				min_income:234223,
// 				caste:"general",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"agriculture",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,
// 				min_income:234223,
// 				caste:"general",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"agriculture",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,
// 				min_income:234223,
// 				caste:"general",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"business",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,
// 				min_income:234223,
// 				caste:"sc",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"business",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,
// 				min_income:234223,
// 				caste:"sc",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"business",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,
// 				min_income:234223,
// 				caste:"st",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"business",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,
// 				min_income:234223,
// 				caste:"st",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"business",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,
// 				min_income:234223,
// 				caste:"st",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"education",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,
// 				min_income:234223,
// 				caste:"st",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"education",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,
// 				min_income:234223,
// 				caste:"st",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"health",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			{
// 				scheme_name:"scheme ka naaam",
// 				about_scheme:"scheme ke baarein me",
// 				min_age:20,
// 				min_income:234223,
// 				caste:"st",
// 				gender:"vo bhi small me no spaces (male) aisa",
// 				scheme_sector:"banking",
// 				scheme_url:"gov ki website ka link",
// 			},
// 			//aage aise hi add karte rehna
// ]

export default schemes;